### ISSUE TITLE
Is jspm needed?

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fitToParent#1]
Hey @selfagency , thought you could help with this. I've rolled the PR you made into the latest version, but not sure if we need the jspm declarations now that it's a registered module (I've never used jspm.)

Can you offer any insight here?

**Comment by selfagency** [comment]
it is still necessary because your script has no exports. it could be put in the [jspm registry](https://github.com/jspm/registry) as an override if you prefer not to have the jspm references in your package.json.

**Comment by johndigital** [comment]
Totally fine to keep it in if it helps jspm users!

It actually does have an export now though, exporting the core function here: https://github.com/funkhaus/fitToParent/blob/master/fitToParent.js#L100

This works for a something like a webpack build env, or just plain node but maybe still does not work for what jspm needs?

**Comment by selfagency** [comment]
kill it for the moment and let me try it again without an override?

**Comment by johndigital** [comment]
done, let me know!

**Comment by johndigital** [comment]
@selfagency going to close this and leave jspm declaration out for now. Please let me know if it needs to be added back in!
